# Generated by Django 5.2 on 2025-05-04 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=55)),
                ('region', models.CharField(max_length=55)),
            ],
            options={
                'db_table': 'Airport',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('salutation', models.CharField(max_length=3)),
                ('firstname', models.CharField(max_length=10)),
                ('lastname', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=1)),
                ('email', models.CharField(max_length=55)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedId', models.IntegerField(primary_key=True, serialize=False)),
                ('flightNo', models.CharField(max_length=5)),
                ('depDate', models.DateTimeField()),
                ('arrDate', models.DateTimeField()),
                ('flightTime', models.TimeField()),
                ('seats', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest', to='booking.airport')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='booking.airport')),
            ],
            options={
                'db_table': 'Schedule',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_bookings', to='booking.customer')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_bookings', to='booking.schedule')),
            ],
            options={
                'db_table': 'Booking',
            },
        ),
    ]
