# Generated by Django 5.2 on 2025-05-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='id',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_ref',
            field=models.CharField(default='BKTMP', max_length=5, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
